### ISSUE TITLE
关于 500错误

### ISSUE THREAD

**Issue by leyafo** [chloerei/writings#12]
我把app 用nginx跑起来后，hosts域名指向也设置了。但是进入首页的时候显示 Page not Found。
下面是后台打印的信息
ActionView::MissingTemplate (Missing template errors/500 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"
  ):
  app/controllers/application_controller.rb:28:in `render_500'
  app/middleware/conditional_ssl.rb:9:in`call'

我的环境是ubuntu 12.04 server 是架在虚拟机上的。
另外nginx设置中 root指向的是public。

**Comment by chloerei** [comment]
这个错误日志和你看到的错误可能不是同一个。你再翻翻对应你访问路径的那条日志。

**Comment by leyafo** [comment]
I, [2013-12-21T15:15:02.602433 #13301]  INFO -- : Started GET "/" for 192.168.12.105 at 2013-12-21 15:15:02 +0000
I, [2013-12-21T15:15:02.605172 #13301]  INFO -- : Processing by Site::ArticlesController#index as HTML
I, [2013-12-21T15:15:02.608524 #13301]  INFO -- :   Rendered errors/404.html.slim within layouts/error (0.2ms)
I, [2013-12-21T15:15:02.609674 #13301]  INFO -- : Completed 404 Not Found in 4ms (Views: 2.2ms)
I, [2013-12-21T15:15:02.896972 #13301]  INFO -- : Started GET "/stylesheets/error.css" for 192.168.12.105 at 2013-12-21 15:15:02 +0000
I, [2013-12-21T15:15:02.898310 #13301]  INFO -- : Processing by ErrorsController#not_found as CSS
I, [2013-12-21T15:15:02.899436 #12460]  INFO -- : Started GET "/images/favicon.png" for 192.168.12.105 at 2013-12-21 15:15:02 +0000
I, [2013-12-21T15:15:02.901036 #12460]  INFO -- : Processing by ErrorsController#not_found as PNG
I, [2013-12-21T15:15:02.901429 #13301]  INFO -- :   Parameters: {"a"=>"stylesheets/error"}
I, [2013-12-21T15:15:02.901558 #12460]  INFO -- :   Parameters: {"a"=>"images/favicon"}
I, [2013-12-21T15:15:02.902595 #12460]  INFO -- : Missing template errors/404 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"

I, [2013-12-21T15:15:02.903529 #12460]  INFO -- : Completed 500 Internal Server Error in 2ms
I, [2013-12-21T15:15:02.904163 #13301]  INFO -- : Missing template errors/404 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:css], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"

I, [2013-12-21T15:15:02.904804 #13301]  INFO -- : Completed 500 Internal Server Error in 2ms
F, [2013-12-21T15:15:02.906955 #12460] FATAL -- :
ActionView::MissingTemplate (Missing template errors/500 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"
  ):
  app/controllers/application_controller.rb:28:in `render_500'
  app/middleware/conditional_ssl.rb:9:in`call'

F, [2013-12-21T15:15:02.909519 #13301] FATAL -- :
ActionView::MissingTemplate (Missing template errors/500 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:css], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"
  ):
  app/controllers/application_controller.rb:28:in `render_500'
  app/middleware/conditional_ssl.rb:9:in`call'

I, [2013-12-21T15:15:03.199560 #13301]  INFO -- : Started GET "/favicon.png" for 192.168.12.105 at 2013-12-21 15:15:03 +0000
I, [2013-12-21T15:15:03.201216 #13301]  INFO -- : Processing by ErrorsController#not_found as PNG
I, [2013-12-21T15:15:03.201889 #13301]  INFO -- :   Parameters: {"a"=>"favicon"}
I, [2013-12-21T15:15:03.202926 #13301]  INFO -- : Missing template errors/404 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"

I, [2013-12-21T15:15:03.204040 #13301]  INFO -- : Completed 500 Internal Server Error in 2ms
F, [2013-12-21T15:15:03.205966 #13301] FATAL -- :
ActionView::MissingTemplate (Missing template errors/500 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"
  ):
  app/controllers/application_controller.rb:28:in `render_500'
  app/middleware/conditional_ssl.rb:9:in`call'

I, [2013-12-21T15:15:03.507966 #13301]  INFO -- : Started GET "/favicon.png" for 192.168.12.105 at 2013-12-21 15:15:03 +0000
I, [2013-12-21T15:15:03.509288 #13301]  INFO -- : Processing by ErrorsController#not_found as PNG
I, [2013-12-21T15:15:03.509565 #13301]  INFO -- :   Parameters: {"a"=>"favicon"}
I, [2013-12-21T15:15:03.510184 #13301]  INFO -- : Missing template errors/404 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"

I, [2013-12-21T15:15:03.510812 #13301]  INFO -- : Completed 500 Internal Server Error in 1ms
F, [2013-12-21T15:15:03.512464 #13301] FATAL -- :
ActionView::MissingTemplate (Missing template errors/500 with {:locale=>[:en, :"zh-CN", :zh], :formats=>[:png], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :jbuilder, :coffee]}. Searched in:
- "/vagrant_code/rails/writings/app/views"
- "/home/vagrant/.rvm/gems/ruby-2.0.0-p247/gems/kaminari-0.14.1/app/views"
- "/vagrant_code/rails/writings"
- "/"
  ):
  app/controllers/application_controller.rb:28:in `render_500'
  app/middleware/conditional_ssl.rb:9:in`call'

# 

这个是访问的全部日志。

**Comment by chloerei** [comment]
```
I, [2013-12-21T15:15:02.602433 #13301] INFO -- : Started GET "/" for 192.168.12.105 at 2013-12-21 15:15:02 +0000
I, [2013-12-21T15:15:02.605172 #13301] INFO -- : Processing by Site::ArticlesController#index as HTML
I, [2013-12-21T15:15:02.608524 #13301] INFO -- : Rendered errors/404.html.slim within layouts/error (0.2ms)
I, [2013-12-21T15:15:02.609674 #13301] INFO -- : Completed 404 Not Found in 4ms (Views: 2.2ms)
```

如果你访问的是网站首页（而不是个人首页），而这里显示路由访问到了个人首页，说明 config/app_config.yml 里面设置的 host 没有对应网站主域名。

**Comment by chloerei** [comment]
这样个人域名会变成 username.www.writings.dev 哦，可以去掉 www 或者自己改掉这一块代码。

**Comment by leyafo** [comment]
我已经改回来了，原来是config/app_config.yml里的host，服务器host，访问客户端host 指向要是同一个域名。
