### ISSUE TITLE
有关用户注册……

### ISSUE THREAD

**Issue by cassiuschen** [chloerei/writings#4]
看来是我学业不精啊…………翻了3天源代码了愣是没找到有关用户注册的后台代码在哪里……………………求指教………………

**Comment by chloerei** [comment]
先看路由

https://github.com/chloerei/writings/blob/dafbb6b48291df6a0067b9da15795550cc930460/config/routes.rb#L24

``` ruby
get 'signup' => 'users#new', :as => :signup
```

然后看 UsersController#new /#create

**Comment by cassiuschen** [comment]
感谢！！
