### ISSUE TITLE
编辑器的引号，怎么结束？

### ISSUE THREAD

**Issue by guotie** [chloerei/writings#8]
输入引号之后，必须在引号下有一行，否则输入的内容就会一直被引起来

**Comment by guotie** [comment]
是bug吗

**Comment by chloerei** [comment]
用光标移动到下一行，应该会跳出引号。引号后预留了一行空行，如果这行空行删除了那就悲剧了，只能先去掉引用框。

算是个缺陷吧，可视化编辑很不好处理。

**Comment by guotie** [comment]
ok
