### ISSUE TITLE
想把这个编辑器独立出来，该怎么做

### ISSUE THREAD

**Issue by guotie** [chloerei/writings#9]
如题

**Comment by chloerei** [comment]
先看 https://github.com/chloerei/writings/blob/master/app/assets/javascripts/dashboard/articles/edit.js.coffee ，跟编辑器有关的是这段代码

``` coffeescript
    @editor = new Editor(
      toolbar: "#toolbar"
      editable: "#editarea .article"
    )
    @imageUploader = new Editor.ImageUploader(@editor)
    @linkCreator = new Editor.LinkCreator(@editor)
```

这段代码初始化了一个 editor 对象，把监控对象设为 `#toolbar` 和 `#editarea .article`，然后再安装两个 plugin：ImageUploader 和 LinkCreator。之所以把这两个做成插件是因为以前也有将编辑器抽离的想法，这两个功能生成的对话框跟 writings.io 绑定太紧密，所以可以抽离，下面只看编辑器，不管这两个 plugin 了。

Editor 相关的代码是 app/assets/javascript 下的 `editor.js.coffee` 和 `editor/*.js.coffee` 。要独立编辑器，就搭一个 demo 页面，引用这几个文件**编译后**的 javascript 文件，然后初始化。demo 页面的格式参考 https://github.com/chloerei/writings/blob/master/app/views/dashboard/articles/edit.html.slim 的这一部分

``` slim
    = render :partial => 'dashboard/articles/edit/toolbar'
    #editarea
      .scrollable
        .editor-container
          article.article contentEditable="true" spellcheck="false" data-id=(@article.token) data-save-count=(@article.save_count) data-urlname=(@article.urlname) data-status=(@article.status) class=(@article.new_record? ? 'init' : nil) data-space=(@space.to_param) data-is-workspace=(@space.members.count > 1) data-current-user-name=(current_user.name)
            = article_format_body @article.body
```

toolbar 部分还要打开局部模板看结构。toolbar 的功能绑定是根据 `data-command='bold'` 元素的 click 事件，跟 https://github.com/chloerei/writings/blob/master/app/assets/javascripts/editor/formator.js.coffee 里的方法相对应的。

不知道你看明白了没有，我想表达的是：抽出来可不容易。

**Comment by guotie** [comment]
了解，非常感谢！
